// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpjwnMfu66n5LlBc7G7-OwvNeVPHEM-jI',
    appId: '1:1002495583309:web:f00e44d564eb53fb1ae804',
    messagingSenderId: '1002495583309',
    projectId: 'dairytrace-9862d',
    authDomain: 'dairytrace-9862d.firebaseapp.com',
    storageBucket: 'dairytrace-9862d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzcPTNIJG6yEw8Oseww_vLKI9FgKrdXIs',
    appId: '1:1002495583309:android:1401f1913b84ccbd1ae804',
    messagingSenderId: '1002495583309',
    projectId: 'dairytrace-9862d',
    storageBucket: 'dairytrace-9862d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH0g5yo2vfiubR3QZxc3uovrrSkO_JD8k',
    appId: '1:1002495583309:ios:e0d9909c936b3c071ae804',
    messagingSenderId: '1002495583309',
    projectId: 'dairytrace-9862d',
    storageBucket: 'dairytrace-9862d.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH0g5yo2vfiubR3QZxc3uovrrSkO_JD8k',
    appId: '1:1002495583309:ios:e0d9909c936b3c071ae804',
    messagingSenderId: '1002495583309',
    projectId: 'dairytrace-9862d',
    storageBucket: 'dairytrace-9862d.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpjwnMfu66n5LlBc7G7-OwvNeVPHEM-jI',
    appId: '1:1002495583309:web:73da0b52f988fe151ae804',
    messagingSenderId: '1002495583309',
    projectId: 'dairytrace-9862d',
    authDomain: 'dairytrace-9862d.firebaseapp.com',
    storageBucket: 'dairytrace-9862d.firebasestorage.app',
  );
}
